# Generated by Django 5.1.6 on 2025-02-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_remove_employee_id_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
